name: mapbox_gl_web
description: Web platform implementation of mapbox_gl
version: 0.16.0
homepage: https://github.com/tobrun/flutter-mapbox-gl

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/devmobile-vulog/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
      ref: 62311c4ccc540d5706a4dd2b2f5d8c9877a60139
  mapbox_gl_dart: ^0.2.1
  image: ^3.0.0

dependency_overrides:
  mapbox_gl_platform_interface:
    path: ../mapbox_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"